### ISSUE TITLE
Error: Open Failed

### ISSUE THREAD

**Issue by safanmomin** [itsKaynine/cordova-plugin-bixolon-printing#1]
Hi, I've just started working on your plugin but every time I try to connect to the printer it calls the error callback function and gives the following error: 
`Error: open Failed`

I am trying to implement a simple connect example that you mentioned: 
```
                cordova.plugins.BixolonPrinting.connect(function () {
                    alert('Success')
                }, function (err) {
                    alert('Error: '+err)
                }, {
                    logicalDeviceName: 'SRP-350III',
                    deviceBus: cordova.plugins.BixolonPrinting.DEVICE_BUS.USB, // cordova.plugins.BixolonPrinting.DEVICE_BUS
                    address: '',
                    secure: true
                });
```
I am using Bixolon SRP-350II USB printer.

**Comment by safanmomin** [comment]
Update @itsKaynine : I just tested and it prints fine with LAN printer. Quick question how to print text instead of an image?

**Comment by itsKaynine** [comment]
@safanmomin Hi, I wrote this plugin for my freelance job which requires a very specific formatting of the printed content. This is why I decided to only wrap the image printing method in Java for now. What I did in Cordova is create an image in HTML canvas then convert it to Base64 using toDataURL() function.

If I have time in the future I would absolutely update the plugin to support text printing.

You can also contribute to the repo. All the printing methods such as printBarcode can be found here
https://github.com/emigonza/JavaPOS/blob/master/src/jpos/POSPrinter.java
