### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by san0suke** [itsKaynine/cordova-plugin-bixolon-printing#2]
Your are missing the comma in the wifi example:
base64Image: b64Image -> base64Image: b64Image,

// Connect to printer
cordova.plugins.BixolonPrinting.connect(
    function(res) {

        // Printing options
        var printObj = {
            base64Image: b64Image,
            width: 500,
            brightness: 50,
            alignment: cordova.plugins.BixolonPrinting.ALIGNMENT.CENTER,
        };

        // Perform printing
        cordova.plugins.BixolonPrinting.printBitmap(
            function(res) { 
                alert("SUCCESS"); 

                // ... Do other things or just disconnect()
            }, 
            alertError, 
            printObj
        );
    },
    alertError,
    connection
);

**Comment by itsKaynine** [comment]
Thanks! I'll fix it now.
